export const AUTH_SIGN_UP = "AUTH_SIGN_UP";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD";
export const AUTH_LINK_GOOGLE = "AUTH_LINK_GOOGLE";
export const AUTH_LINK_FACEBOOK = "AUTH_LINK_FACEBOOK";
export const AUTH_UNLINK_GOOGLE = "AUTH_UNLINK_GOOGLE";
export const AUTH_UNLINK_FACEBOOK = "AUTH_UNLINK_FACEBOOK";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const DASHBOARD_GET_DATA = "DASHBOARD_GET_DATA";

// Filter types
export const SET_SUBCATEGORIES = "SET_SUBCATEGORIES";
